/**
 * Surowce: makra na 100 g i wagi miar domowych.
 *
 * PO CO TO JEST. Przepisy z książki kucharskiej mówią "2 łyżki masła",
 * a nie "30 g masła". Dziennik diety liczy w gramach. Ta tabela jest jedynym
 * miejscem, w którym jedno zamienia się w drugie - i jedynym miejscem
 * z wartościami odżywczymi surowców, bo Open Food Facts to baza produktów
 * z kodem kreskowym i zwykłej mąki bez opakowania w niej nie ma.
 *
 * SKĄD LICZBY. Wartości przeciętne dla surowca w stanie, w jakim trafia do
 * garnka (mięso surowe, kasza sucha, warzywa świeże). Talerz u babci będzie
 * inny i aplikacja mówi o tym wprost, zamiast udawać precyzję.
 *
 * POLA:
 *   n  nazwa kanoniczna - trafia do foods i do składnika przepisu
 *   k  kcal / 100 g,  b  białko,  w  węglowodany,  t  tłuszcz
 *   m  wagi miar domowych w gramach; nadpisują MIARY_DOMYSLNE
 *   a  formy, w jakich składnik występuje w przepisach (polska odmiana)
 *   s  waga jednej sztuki w gramach, gdy sztuka ma sens ("2 jajka")
 *   kat  kategoria - tylko do porządkowania wyszukiwarki
 *   x    powód, dla którego kalorie NIE wynikają z reguły 4/4/9:
 *        "błonnik" (przyprawy to głównie błonnik, a ten daje ok. 2 kcal/g,
 *        nie 4) albo "alkohol" (7 kcal/g, a alkoholu nie ma wśród makro).
 *        Test spójności pomija te pozycje - i tylko te.
 */

/**
 * Miary domowe, gdy surowiec nie mówi inaczej.
 *
 * Łyżka to 15 g dla płynów i 10 g dla rzeczy sypkich, więc wartość domyślna
 * jest zawsze którymś z tych dwóch przybliżeń - dlatego każdy często używany
 * surowiec ma własną wagę w polu `m`.
 */
export const MIARY_DOMYSLNE = {
  łyżka: 15,
  łyżeczka: 5,
  szklanka: 250,
  kubek: 250,
  szczypta: 0.5,
  garść: 30,
  ząbek: 4,
  plaster: 20,
  kromka: 35,
  puszka: 400,
  słoik: 300,
  opakowanie: 200,
  pęczek: 30,
  listek: 1,
  gałązka: 3,
  kieliszek: 50,
  łodyga: 40,
  główka: 500,
  sztuka: 100,
};

export const SUROWCE = [
  // --- Mąki, kasze, makarony, pieczywo ---
  { n: "Mąka pszenna", k: 364, b: 10.3, w: 76.3, t: 1.0, kat: "Mąki i kasze",
    m: { łyżka: 10, łyżeczka: 3, szklanka: 130 },
    a: ["mąka", "mąki", "mąkę", "mąką", "mąka pszenna", "mąki pszennej", "mąka tortowa",
        "mąki tortowej", "mąka krupczatka", "mąka poznańska", "mąka orkiszowa",
        "mąki orkiszowej"] },
  { n: "Mąka żytnia", k: 349, b: 8.2, w: 75.9, t: 1.4, kat: "Mąki i kasze",
    m: { łyżka: 10, szklanka: 125 }, a: ["mąka żytnia"] },
  { n: "Mąka ziemniaczana", k: 343, b: 0.5, w: 83.1, t: 0.1, kat: "Mąki i kasze",
    m: { łyżka: 12, szklanka: 150 }, a: ["mąka ziemniaczana", "skrobia ziemniaczana",
        "skrobi ziemniaczanej", "skrobia kukurydziana", "skrobi kukurydzianej"] },
  { n: "Mąka kukurydziana", k: 361, b: 6.9, w: 76.8, t: 3.9, kat: "Mąki i kasze",
    m: { łyżka: 10, szklanka: 120 }, a: ["mąka kukurydziana"] },
  { n: "Bułka tarta", k: 383, b: 12.5, w: 71.0, t: 4.7, kat: "Mąki i kasze",
    m: { łyżka: 12, szklanka: 130 }, a: ["bułka tarta", "tarta bułka"] },
  { n: "Kasza gryczana", k: 336, b: 12.6, w: 69.3, t: 2.6, kat: "Mąki i kasze",
    m: { łyżka: 15, szklanka: 180 }, a: ["kasza gryczana", "kaszy gryczanej", "gryka"] },
  { n: "Kasza jęczmienna", k: 345, b: 8.0, w: 74.0, t: 1.4, kat: "Mąki i kasze",
    m: { szklanka: 180 }, a: ["kasza jęczmienna", "kaszy jęczmiennej", "kasza perłowa", "pęczak"] },
  { n: "Kasza jaglana", k: 346, b: 10.5, w: 71.6, t: 3.3, kat: "Mąki i kasze",
    m: { szklanka: 180 }, a: ["kasza jaglana", "kaszy jaglanej", "jaglana"] },
  { n: "Kasza manna", k: 360, b: 9.8, w: 76.0, t: 1.2, kat: "Mąki i kasze",
    m: { łyżka: 12, szklanka: 160 }, a: ["kasza manna", "manna"] },
  { n: "Ryż biały", k: 344, b: 6.7, w: 78.9, t: 0.7, kat: "Mąki i kasze",
    m: { szklanka: 190 }, a: ["ryż", "ryżu", "ryż biały", "ryż długoziarnisty", "ryż basmati"] },
  { n: "Ryż brązowy", k: 331, b: 6.8, w: 71.1, t: 2.7, kat: "Mąki i kasze",
    m: { szklanka: 190 }, a: ["ryż brązowy", "ryż pełnoziarnisty"] },
  { n: "Makaron", k: 363, b: 12.5, w: 71.5, t: 1.8, kat: "Mąki i kasze",
    a: ["makaron", "makaron spaghetti", "spaghetti", "makaron nitki", "makaron świderki",
        "makaron penne", "makaron kokardki", "makaron wstążki", "makaron ryżowy"] },
  { n: "Płatki owsiane", k: 366, b: 11.9, w: 60.0, t: 7.2, kat: "Mąki i kasze",
    m: { łyżka: 10, szklanka: 90 }, a: ["płatki owsiane", "płatków owsianych", "owsianka"] },
  { n: "Chleb pszenny", k: 265, b: 8.5, w: 49.0, t: 3.2, kat: "Pieczywo",
    m: { kromka: 35 }, a: ["chleb", "chleba", "chleb pszenny", "bułka paryska", "bagietka",
        "chleb tostowy", "kromki chleba", "kromek"] },
  { n: "Chleb żytni razowy", k: 223, b: 6.1, w: 43.0, t: 1.7, kat: "Pieczywo",
    m: { kromka: 40 }, a: ["chleb razowy", "chleb żytni", "razowiec"] },
  { n: "Bułka pszenna", k: 279, b: 8.6, w: 55.0, t: 2.6, kat: "Pieczywo", s: 60,
    a: ["bułka", "bułki", "bułka kajzerka", "kajzerka"] },

  // --- Nabiał i jaja ---
  { n: "Mleko 3,2%", k: 61, b: 3.3, w: 4.7, t: 3.2, kat: "Nabiał",
    m: { szklanka: 250, łyżka: 15 }, a: ["mleko", "mleko 3,2%", "mleko pełnotłuste", "mleko krowie"] },
  { n: "Mleko 2%", k: 51, b: 3.3, w: 4.8, t: 2.0, kat: "Nabiał",
    m: { szklanka: 250 }, a: ["mleko 2%", "mleko półtłuste"] },
  { n: "Mleko zagęszczone słodzone", k: 321, b: 7.9, w: 55.0, t: 8.7, kat: "Nabiał",
    m: { puszka: 400, łyżka: 20 }, a: ["mleko zagęszczone", "mleko skondensowane"] },
  { n: "Śmietana 18%", k: 184, b: 2.6, w: 3.6, t: 18.0, kat: "Nabiał",
    m: { łyżka: 15, szklanka: 240, opakowanie: 200 },
    a: ["śmietana", "śmietany", "śmietana 18%", "śmietana kwaśna"] },
  { n: "Śmietana 30%", k: 292, b: 2.3, w: 3.2, t: 30.0, kat: "Nabiał",
    m: { łyżka: 15, szklanka: 240, opakowanie: 200 },
    a: ["śmietana 30%", "śmietana kremówka", "kremówka", "śmietanka kremówka", "śmietana 36%"] },
  { n: "Śmietanka 12%", k: 127, b: 2.9, w: 4.0, t: 12.0, kat: "Nabiał",
    m: { łyżka: 15, szklanka: 240 }, a: ["śmietanka", "śmietanka 12%", "śmietanka do kawy"] },
  { n: "Jogurt naturalny", k: 61, b: 3.5, w: 4.7, t: 3.3, kat: "Nabiał",
    m: { łyżka: 20, opakowanie: 175 }, a: ["jogurt", "jogurt naturalny", "jogurt grecki"] },
  { n: "Kefir", k: 51, b: 3.3, w: 4.1, t: 2.0, kat: "Nabiał",
    m: { szklanka: 250, opakowanie: 400 }, a: ["kefir"] },
  { n: "Maślanka", k: 40, b: 3.3, w: 4.7, t: 0.9, kat: "Nabiał",
    m: { szklanka: 250 }, a: ["maślanka"] },
  { n: "Masło", k: 735, b: 0.7, w: 0.7, t: 82.0, kat: "Tłuszcze",
    m: { łyżka: 15, łyżeczka: 5, kostka: 200, opakowanie: 200 },
    a: ["masło", "masło extra", "masło klarowane"] },
  { n: "Margaryna", k: 717, b: 0.2, w: 0.7, t: 80.0, kat: "Tłuszcze",
    m: { łyżka: 15, kostka: 250, opakowanie: 250 }, a: ["margaryna"] },
  { n: "Twaróg półtłusty", k: 133, b: 18.7, w: 3.7, t: 4.7, kat: "Nabiał",
    m: { opakowanie: 250 }, a: ["twaróg", "ser biały", "twaróg półtłusty", "serek wiejski"] },
  { n: "Ser żółty", k: 358, b: 25.0, w: 1.3, t: 28.0, kat: "Nabiał",
    m: { plaster: 20 }, a: ["ser żółty", "sera żółtego", "ser gouda", "ser edamski", "żółty ser", "ser",
        "sera", "tarty ser", "tartego sera", "ser tarty"] },
  { n: "Ser feta", k: 264, b: 14.2, w: 4.1, t: 21.3, kat: "Nabiał",
    m: { opakowanie: 200 }, a: ["feta", "ser feta", "ser typu feta"] },
  { n: "Ser mozzarella", k: 280, b: 22.0, w: 2.2, t: 20.0, kat: "Nabiał",
    m: { opakowanie: 125, kulka: 125 }, a: ["mozzarella", "ser mozzarella"] },
  { n: "Ser parmezan", k: 392, b: 35.8, w: 3.2, t: 25.8, kat: "Nabiał",
    m: { łyżka: 6 }, a: ["parmezan", "ser parmezan", "grana padano"] },
  { n: "Ser brie", k: 334, b: 20.8, w: 0.5, t: 27.7, kat: "Nabiał",
    a: ["brie", "ser brie", "camembert"] },
  { n: "Serek śmietankowy", k: 253, b: 6.2, w: 4.1, t: 23.4, kat: "Nabiał",
    m: { opakowanie: 200, łyżka: 20 }, a: ["serek śmietankowy", "philadelphia", "serek kremowy",
        "ser ricotta", "ricotta", "sera ricotta", "mascarpone",
        "serek topiony", "ser topiony"] },
  { n: "Jajko kurze", k: 143, b: 12.6, w: 0.7, t: 9.5, kat: "Nabiał", s: 55,
    a: ["jajko", "jajka", "jajek", "jaj", "jaja", "jajo", "jajku", "jajkami", "jajko kurze"] },
  { n: "Żółtko jaja", k: 322, b: 15.9, w: 3.6, t: 26.5, kat: "Nabiał", s: 18,
    a: ["żółtko", "żółtka"] },
  { n: "Białko jaja", k: 52, b: 10.9, w: 0.7, t: 0.2, kat: "Nabiał", s: 33,
    a: ["białko", "białka", "białko jaja"] },

  // --- Tłuszcze ---
  { n: "Olej rzepakowy", k: 884, b: 0, w: 0, t: 100, kat: "Tłuszcze",
    m: { łyżka: 10, łyżeczka: 4, szklanka: 220 },
    a: ["olej", "oleju", "olej rzepakowy", "olej słonecznikowy", "olej roślinny",
        "tłuszcz", "tłuszczu", "wybranego tłuszczu"] },
  { n: "Oliwa z oliwek", k: 884, b: 0, w: 0, t: 100, kat: "Tłuszcze",
    m: { łyżka: 10, łyżeczka: 4 }, a: ["oliwa", "oliwa z oliwek"] },
  { n: "Smalec", k: 900, b: 0, w: 0, t: 100, kat: "Tłuszcze",
    m: { łyżka: 13 }, a: ["smalec", "smalcu"] },

  // --- Mięso, drób, ryby, wędliny ---
  { n: "Pierś z kurczaka", k: 110, b: 21.5, w: 0, t: 2.6, kat: "Mięso", s: 180,
    a: ["pierś z kurczaka", "filet z kurczaka", "piersi z kurczaka", "kurczak",
        "filety z kurczaka", "mięso z kurczaka"] },
  { n: "Udko z kurczaka", k: 168, b: 17.5, w: 0, t: 11.0, kat: "Mięso", s: 130,
    a: ["udko", "udka", "udka z kurczaka", "podudzia", "ćwiartki z kurczaka"] },
  { n: "Kurczak cały", k: 160, b: 18.6, w: 0, t: 9.5, kat: "Mięso",
    a: ["kurczak cały", "kura", "kurczaka"] },
  { n: "Wątróbka drobiowa", k: 128, b: 19.0, w: 1.4, t: 4.8, kat: "Mięso",
    a: ["wątróbka", "wątróbka drobiowa", "wątróbka z kurczaka", "wątróbki"] },
  { n: "Kaczka", k: 236, b: 18.3, w: 0, t: 18.0, kat: "Mięso",
    a: ["kaczka", "kaczki", "mięso z kaczki", "piersi z kaczki"] },
  { n: "Gęś", k: 305, b: 15.9, w: 0, t: 27.0, kat: "Mięso", a: ["gęś", "gęsi"] },
  { n: "Indyk pierś", k: 105, b: 22.6, w: 0, t: 1.3, kat: "Mięso",
    a: ["indyk", "pierś z indyka", "filet z indyka"] },
  { n: "Schab wieprzowy", k: 152, b: 21.0, w: 0, t: 7.4, kat: "Mięso",
    a: ["schab", "schab wieprzowy", "polędwiczka wieprzowa", "kotlety schabowe"] },
  { n: "Łopatka wieprzowa", k: 214, b: 17.6, w: 0, t: 16.0, kat: "Mięso",
    a: ["łopatka", "łopatka wieprzowa", "mięso wieprzowe", "wieprzowina", "karkówka",
        "kark wieprzowy", "karku wieprzowego", "mielonego karku wieprzowego"] },
  { n: "Boczek surowy", k: 393, b: 12.6, w: 0, t: 37.5, kat: "Mięso",
    m: { plaster: 25 }, a: ["boczek", "boczku", "boczek surowy", "boczek wędzony", "wędzony boczek",
        "wędzonego boczku", "boczku wędzonego", "żeberka", "żeberek"] },
  { n: "Mięso mielone wieprzowo-wołowe", k: 240, b: 17.0, w: 0, t: 19.0, kat: "Mięso",
    a: ["mięso mielone", "mięso mielone wieprzowo-wołowe", "farsz mięsny", "mięsa mielonego"] },
  { n: "Wołowina", k: 175, b: 20.5, w: 0, t: 10.0, kat: "Mięso",
    a: ["wołowina", "wołowiny", "mięso wołowe", "rostbef", "antrykot", "łopatka wołowa",
        "pręga wołowa", "polędwica wołowa", "polędwicy wołowej"] },
  { n: "Mielona wołowina", k: 187, b: 20.0, w: 0, t: 12.0, kat: "Mięso",
    a: ["mielona wołowina", "wołowina mielona", "mięso mielone wołowe"] },
  { n: "Cielęcina", k: 131, b: 20.4, w: 0, t: 5.5, kat: "Mięso",
    a: ["cielęcina", "mięso cielęce"] },
  { n: "Kiełbasa", k: 298, b: 15.0, w: 1.5, t: 26.0, kat: "Wędliny",
    a: ["kiełbasa", "kiełbaski", "kiełbasa podwawelska", "chorizo", "kabanosy"] },
  { n: "Szynka", k: 108, b: 18.5, w: 1.2, t: 3.3, kat: "Wędliny",
    m: { plaster: 20 }, a: ["szynka", "szynka gotowana", "szynka konserwowa"] },
  { n: "Szynka parmeńska", k: 268, b: 27.0, w: 0.4, t: 17.5, kat: "Wędliny",
    m: { plaster: 15 }, a: ["szynka parmeńska", "prosciutto", "pancetta", "szynka dojrzewająca"] },
  { n: "Łosoś", k: 208, b: 20.0, w: 0, t: 13.0, kat: "Ryby",
    a: ["łosoś", "filet z łososia", "łososia"] },
  { n: "Śledź solony", k: 217, b: 17.0, w: 0, t: 16.5, kat: "Ryby",
    a: ["śledź", "śledzie", "filety śledziowe"] },
  { n: "Dorsz", k: 82, b: 17.8, w: 0, t: 0.7, kat: "Ryby",
    a: ["dorsz", "filet z dorsza", "ryba", "filety rybne", "mintaj", "morszczuk"] },
  { n: "Makrela wędzona", k: 305, b: 20.7, w: 0, t: 24.0, kat: "Ryby",
    a: ["makrela", "makrela wędzona", "ryba wędzona", "wędzona ryba", "wędzonej ryby",
        "ryby wędzonej"] },
  { n: "Sum", k: 143, b: 16.4, w: 0, t: 8.5, kat: "Ryby", a: ["sum", "suma"] },
  { n: "Karmazyn", k: 94, b: 19.0, w: 0, t: 1.6, kat: "Ryby", a: ["karmazyn", "karmazyna"] },
  { n: "Pstrąg", k: 119, b: 19.9, w: 0, t: 4.3, kat: "Ryby", a: ["pstrąg", "pstrąga"] },
  { n: "Tuńczyk w sosie własnym", k: 116, b: 25.5, w: 0, t: 1.0, kat: "Ryby",
    m: { puszka: 170 }, a: ["tuńczyk", "tuńczyk w sosie własnym"] },
  { n: "Krewetki", k: 99, b: 20.9, w: 0.2, t: 1.7, kat: "Ryby",
    a: ["krewetki", "owoce morza"] },

  // --- Warzywa ---
  { n: "Cebula", k: 40, b: 1.1, w: 9.3, t: 0.1, kat: "Warzywa", s: 100,
    a: ["cebula", "cebule", "cebuli", "cebulek", "cebulka", "cebulki", "cebula biała",
        "cebula czerwona", "szalotka"] },
  { n: "Czosnek", k: 149, b: 6.4, w: 33.1, t: 0.5, kat: "Warzywa",
    m: { ząbek: 4, główka: 40 }, a: ["czosnek", "ząbki czosnku", "czosnku"] },
  { n: "Marchew", k: 41, b: 0.9, w: 9.6, t: 0.2, kat: "Warzywa", s: 70,
    a: ["marchew", "marchewka", "marchewki", "marchwi"] },
  { n: "Ziemniaki", k: 77, b: 2.0, w: 17.5, t: 0.1, kat: "Warzywa", s: 150,
    a: ["ziemniaki", "ziemniak", "kartofle", "ziemniaków"] },
  { n: "Pietruszka korzeń", k: 75, b: 2.9, w: 17.0, t: 0.8, kat: "Warzywa", s: 80,
    a: ["pietruszka", "korzeń pietruszki", "pietruszka korzeń"] },
  { n: "Natka pietruszki", k: 36, b: 3.0, w: 6.3, t: 0.8, kat: "Warzywa",
    m: { pęczek: 30, łyżka: 4 }, a: ["natka pietruszki", "natka", "pietruszka zielona", "nać pietruszki"] },
  { n: "Seler korzeniowy", k: 42, b: 1.5, w: 9.2, t: 0.3, kat: "Warzywa", s: 400,
    a: ["seler", "seler korzeniowy", "selera"] },
  { n: "Seler naciowy", k: 16, b: 0.7, w: 3.0, t: 0.2, kat: "Warzywa",
    m: { łodyga: 40 }, a: ["seler naciowy", "łodyga selera"] },
  { n: "Por", k: 61, b: 1.5, w: 14.2, t: 0.3, kat: "Warzywa", s: 150, a: ["por", "pora", "pory", "porów"] },
  { n: "Kapusta biała", k: 25, b: 1.3, w: 5.8, t: 0.1, kat: "Warzywa",
    m: { główka: 1000 }, a: ["kapusta", "kapusta biała", "kapusty", "kapusta włoska"] },
  { n: "Kapusta kiszona", k: 19, b: 0.9, w: 4.3, t: 0.1, kat: "Warzywa",
    a: ["kapusta kiszona", "kiszona kapusta"] },
  { n: "Kapusta czerwona", k: 31, b: 1.4, w: 7.4, t: 0.2, kat: "Warzywa",
    m: { główka: 900 }, a: ["kapusta czerwona", "czerwona kapusta", "modra kapusta"] },
  { n: "Pomidory", k: 18, b: 0.9, w: 3.9, t: 0.2, kat: "Warzywa", s: 120,
    a: ["pomidor", "pomidory", "pomidorów", "pomidorki koktajlowe"] },
  { n: "Pomidory z puszki", k: 32, b: 1.6, w: 5.3, t: 0.3, kat: "Warzywa",
    m: { puszka: 400 }, a: ["pomidory z puszki", "pomidory krojone", "passata", "przecier pomidorowy"] },
  { n: "Koncentrat pomidorowy", k: 82, b: 4.3, w: 18.9, t: 0.5, kat: "Warzywa",
    m: { łyżka: 15, opakowanie: 200 }, a: ["koncentrat pomidorowy", "koncentrat",
        "sok pomidorowy", "soku pomidorowego"] },
  { n: "Ogórek świeży", k: 15, b: 0.7, w: 3.6, t: 0.1, kat: "Warzywa", s: 300,
    a: ["ogórek", "ogórki", "ogórek zielony", "ogórek szklarniowy"] },
  { n: "Ogórki kiszone", k: 12, b: 0.6, w: 2.2, t: 0.1, kat: "Warzywa", s: 60,
    a: ["ogórki kiszone", "ogórek kiszony", "ogórki konserwowe"] },
  { n: "Papryka czerwona", k: 31, b: 1.0, w: 6.0, t: 0.3, kat: "Warzywa", s: 150,
    a: ["papryka", "papryka czerwona", "papryki", "papryka żółta", "papryka zielona"] },
  { n: "Papryczka chili", k: 40, b: 1.9, w: 8.8, t: 0.4, kat: "Warzywa", s: 15,
    a: ["papryczka chili", "chili", "papryczka ostra", "papryczki"] },
  { n: "Bakłażan", k: 25, b: 1.0, w: 5.9, t: 0.2, kat: "Warzywa", s: 300,
    a: ["bakłażan", "bakłażany", "oberżyna"] },
  { n: "Cukinia", k: 17, b: 1.2, w: 3.1, t: 0.3, kat: "Warzywa", s: 300,
    a: ["cukinia", "cukinie"] },
  { n: "Dynia", k: 26, b: 1.0, w: 6.5, t: 0.1, kat: "Warzywa", a: ["dynia", "dyni"] },
  { n: "Brokuły", k: 34, b: 2.8, w: 6.6, t: 0.4, kat: "Warzywa", s: 400,
    a: ["brokuł", "brokuły", "brokułów"] },
  { n: "Kalafior", k: 25, b: 1.9, w: 5.0, t: 0.3, kat: "Warzywa", s: 700,
    a: ["kalafior", "kalafiora"] },
  { n: "Szpinak", k: 23, b: 2.9, w: 3.6, t: 0.4, kat: "Warzywa",
    m: { opakowanie: 450, garść: 30 }, a: ["szpinak", "szpinaku", "szpinak mrożony"] },
  { n: "Sałata", k: 15, b: 1.4, w: 2.9, t: 0.2, kat: "Warzywa", s: 250,
    a: ["sałata", "sałata zielona", "sałata lodowa", "sałata masłowa", "rukola"] },
  { n: "Pieczarki", k: 22, b: 3.1, w: 3.3, t: 0.3, kat: "Warzywa",
    a: ["pieczarki", "pieczarek", "grzyby", "grzybów", "boczniaki"] },
  { n: "Grzyby suszone", k: 296, b: 27.6, w: 44.0, t: 3.0, kat: "Warzywa",
    m: { garść: 20 }, a: ["grzyby suszone", "suszone grzyby", "suszone borowiki"] },
  { n: "Buraki", k: 43, b: 1.6, w: 9.6, t: 0.2, kat: "Warzywa", s: 150,
    a: ["burak", "buraki", "buraków", "burak ćwikłowy"] },
  { n: "Fasola szparagowa", k: 31, b: 1.8, w: 7.1, t: 0.1, kat: "Warzywa",
    a: ["fasola szparagowa", "fasolka szparagowa"] },
  { n: "Fasola biała sucha", k: 333, b: 21.4, w: 60.3, t: 1.6, kat: "Warzywa",
    m: { szklanka: 190, puszka: 400 }, a: ["fasola", "fasola biała", "fasoli"] },
  { n: "Groszek zielony", k: 81, b: 5.4, w: 14.5, t: 0.4, kat: "Warzywa",
    m: { puszka: 400 }, a: ["groszek", "groszek zielony", "groszku"] },
  { n: "Soczewica czerwona", k: 352, b: 24.6, w: 63.0, t: 1.1, kat: "Warzywa",
    m: { szklanka: 190 }, a: ["soczewica", "soczewica czerwona"] },
  { n: "Ciecierzyca", k: 364, b: 19.3, w: 60.6, t: 6.0, kat: "Warzywa",
    m: { szklanka: 200, puszka: 400 }, a: ["ciecierzyca", "cieciorka"] },
  { n: "Szparagi", k: 20, b: 2.2, w: 3.9, t: 0.1, kat: "Warzywa",
    m: { pęczek: 500 }, a: ["szparagi", "szparagów"] },
  { n: "Rzodkiewka", k: 16, b: 0.7, w: 3.4, t: 0.1, kat: "Warzywa", s: 15,
    a: ["rzodkiewka", "rzodkiewki", "rzodkiewek"] },
  { n: "Kukurydza konserwowa", k: 86, b: 3.2, w: 19.0, t: 1.2, kat: "Warzywa",
    m: { puszka: 340 }, a: ["kukurydza", "kukurydza konserwowa"] },
  { n: "Oliwki", k: 145, b: 1.0, w: 3.8, t: 15.3, kat: "Warzywa",
    m: { garść: 30 }, a: ["oliwki", "oliwek", "oliwki czarne", "oliwki zielone"] },
  { n: "Awokado", k: 160, b: 2.0, w: 8.5, t: 14.7, kat: "Warzywa", s: 200,
    a: ["awokado"] },
  { n: "Szczypiorek", k: 30, b: 3.3, w: 4.4, t: 0.7, kat: "Warzywa",
    m: { pęczek: 25, łyżka: 4 }, a: ["szczypiorek", "szczypiorku"] },
  { n: "Koperek", k: 43, b: 3.5, w: 7.0, t: 1.1, kat: "Warzywa",
    m: { pęczek: 25, łyżka: 4 }, a: ["koperek", "koper", "koperku"] },

  // --- Owoce ---
  { n: "Jabłka", k: 52, b: 0.3, w: 13.8, t: 0.2, kat: "Owoce", s: 150,
    a: ["jabłko", "jabłka", "jabłek"] },
  { n: "Gruszki", k: 57, b: 0.4, w: 15.2, t: 0.1, kat: "Owoce", s: 170,
    a: ["gruszka", "gruszki", "gruszek"] },
  { n: "Banany", k: 89, b: 1.1, w: 22.8, t: 0.3, kat: "Owoce", s: 120,
    a: ["banan", "banany", "bananów"] },
  { n: "Cytryna", k: 29, b: 1.1, w: 9.3, t: 0.3, kat: "Owoce", s: 100,
    a: ["cytryna", "cytryny", "skórka z cytryny"] },
  { n: "Pomarańcze", k: 47, b: 0.9, w: 11.8, t: 0.1, kat: "Owoce", s: 200,
    a: ["pomarańcza", "pomarańcze", "sok z pomarańczy"] },
  { n: "Truskawki", k: 32, b: 0.7, w: 7.7, t: 0.3, kat: "Owoce",
    m: { szklanka: 150 }, a: ["truskawki", "truskawek"] },
  { n: "Śliwki", k: 46, b: 0.7, w: 11.4, t: 0.3, kat: "Owoce", s: 40,
    a: ["śliwki", "śliwek", "śliwka", "węgierki"] },
  { n: "Wiśnie", k: 50, b: 1.0, w: 12.2, t: 0.3, kat: "Owoce",
    m: { szklanka: 160 }, a: ["wiśnie", "wiśni"] },
  { n: "Czereśnie", k: 63, b: 1.1, w: 16.0, t: 0.2, kat: "Owoce",
    m: { szklanka: 160 }, a: ["czereśnie", "czereśni"] },
  { n: "Jagody", k: 57, b: 0.7, w: 14.5, t: 0.3, kat: "Owoce",
    m: { szklanka: 150 }, a: ["jagody", "jagód", "borówki"] },
  { n: "Maliny", k: 52, b: 1.2, w: 11.9, t: 0.7, kat: "Owoce",
    m: { szklanka: 130 }, a: ["maliny", "malin"] },
  { n: "Rodzynki", k: 299, b: 3.1, w: 79.2, t: 0.5, kat: "Bakalie",
    m: { łyżka: 12, garść: 30 }, a: ["rodzynki", "rodzynek"] },
  { n: "Ananas", k: 50, b: 0.5, w: 13.1, t: 0.1, kat: "Owoce",
    m: { puszka: 400, plaster: 40 }, a: ["ananas", "ananasa"] },
  { n: "Brzoskwinie", k: 39, b: 0.9, w: 9.5, t: 0.3, kat: "Owoce", s: 150,
    a: ["brzoskwinie", "brzoskwinia", "morele"] },

  // --- Bakalie i orzechy ---
  { n: "Orzechy włoskie", k: 654, b: 15.2, w: 13.7, t: 65.2, kat: "Bakalie",
    m: { łyżka: 10, garść: 30 }, a: ["orzechy włoskie", "orzechy", "orzechów"] },
  { n: "Migdały", k: 579, b: 21.2, w: 21.6, t: 49.9, kat: "Bakalie",
    m: { łyżka: 10, garść: 30 }, a: ["migdały", "migdałów", "płatki migdałowe",
        "wiórki migdałowe", "wiórków migdałowych", "płatków migdałowych",
        "uprażonych płatków migdałowych", "migdały mielone"] },
  { n: "Orzeszki ziemne", k: 567, b: 25.8, w: 16.1, t: 49.2, kat: "Bakalie",
    m: { garść: 30 }, a: ["orzeszki ziemne", "orzeszki", "fistaszki"] },
  { n: "Wiórki kokosowe", k: 660, b: 6.9, w: 23.7, t: 64.5, kat: "Bakalie",
    m: { łyżka: 7 }, a: ["wiórki kokosowe", "wiórków kokosowych", "kokos"] },
  { n: "Mak", k: 525, b: 17.9, w: 28.1, t: 41.6, kat: "Bakalie",
    m: { szklanka: 160 }, a: ["mak", "maku"] },
  { n: "Sezam", k: 573, b: 17.7, w: 23.4, t: 49.7, kat: "Bakalie",
    m: { łyżka: 9 }, a: ["sezam", "ziarna sezamu"] },
  { n: "Słonecznik łuskany", k: 584, b: 20.8, w: 20.0, t: 51.5, kat: "Bakalie",
    m: { łyżka: 10, garść: 30 }, a: ["słonecznik", "pestki słonecznika", "nasiona słonecznika"] },

  // --- Cukry, słodycze, wypieki ---
  { n: "Cukier", k: 400, b: 0, w: 100, t: 0, kat: "Słodkie",
    m: { łyżka: 12, łyżeczka: 5, szklanka: 200 },
    a: ["cukier", "cukru", "cukier biały", "cukier kryształ", "cukier brązowy",
        "cukru brązowego", "cukier trzcinowy"] },
  { n: "Cukier puder", k: 400, b: 0, w: 100, t: 0, kat: "Słodkie",
    m: { łyżka: 10, szklanka: 130 }, a: ["cukier puder", "cukru pudru"] },
  { n: "Cukier wanilinowy", k: 400, b: 0, w: 100, t: 0, kat: "Słodkie",
    m: { opakowanie: 16, łyżeczka: 5 }, a: ["cukier wanilinowy", "cukier waniliowy"] },
  { n: "Miód", k: 322, b: 0.3, w: 79.5, t: 0, kat: "Słodkie",
    m: { łyżka: 25, łyżeczka: 8 }, a: ["miód", "miodu"] },
  { n: "Czekolada gorzka", k: 546, b: 7.8, w: 45.9, t: 35.4, kat: "Słodkie",
    m: { tabliczka: 100, kostka: 5 }, a: ["czekolada", "czekolada gorzka", "czekolady", "czekolada deserowa"] },
  { n: "Czekolada mleczna", k: 535, b: 7.6, w: 59.4, t: 29.7, kat: "Słodkie",
    m: { tabliczka: 100 }, a: ["czekolada mleczna", "czekolada biała"] },
  { x: "błonnik", n: "Kakao", k: 228, b: 19.6, w: 57.9, t: 13.7, kat: "Słodkie",
    m: { łyżka: 7, łyżeczka: 2.5 }, a: ["kakao", "kakao gorzkie"] },
  { n: "Dżem", k: 250, b: 0.4, w: 62.0, t: 0.1, kat: "Słodkie",
    m: { łyżka: 20, słoik: 280 }, a: ["dżem", "konfitura", "powidła", "marmolada"] },
  { n: "Budyń w proszku", k: 355, b: 0.5, w: 87.0, t: 0.3, kat: "Słodkie",
    m: { opakowanie: 40 }, a: ["budyń", "budyniu", "budyń w proszku", "kisiel", "kisielu"] },
  { n: "Galaretka w proszku", k: 380, b: 7.0, w: 87.0, t: 0, kat: "Słodkie",
    m: { opakowanie: 75 }, a: ["galaretka", "galaretki"] },
  { n: "Herbatniki", k: 458, b: 6.8, w: 74.0, t: 15.0, kat: "Słodkie",
    s: 8, a: ["herbatniki", "biszkopty", "ciastka", "ciasteczka", "ciasteczek", "krakersy",
        "wafle", "wafli", "ciasteczek karmelowych korzennych"] },
  { n: "Proszek do pieczenia", k: 97, b: 0, w: 23.0, t: 0, kat: "Dodatki",
    m: { łyżeczka: 4, opakowanie: 15 }, a: ["proszek do pieczenia", "proszku do pieczenia"] },
  { n: "Drożdże świeże", k: 105, b: 12.0, w: 12.0, t: 1.5, kat: "Dodatki",
    m: { kostka: 100, opakowanie: 100 }, a: ["drożdże", "drożdży", "drożdże świeże"] },
  { n: "Drożdże suszone", k: 325, b: 40.4, w: 38.2, t: 7.6, kat: "Dodatki",
    m: { opakowanie: 7, łyżeczka: 3 }, a: ["drożdże suszone", "drożdże instant"] },
  { n: "Żelatyna", k: 335, b: 84.0, w: 0, t: 0.1, kat: "Dodatki",
    m: { łyżka: 10, opakowanie: 20 }, a: ["żelatyna", "żelatyny"] },

  // --- Przyprawy i płyny ---
  { n: "Sól", k: 0, b: 0, w: 0, t: 0, kat: "Przyprawy",
    m: { łyżeczka: 6, szczypta: 0.5, łyżka: 18 }, a: ["sól", "soli", "sól morska", "sól i pieprz"] },
  { x: "błonnik", n: "Pieprz czarny", k: 251, b: 10.4, w: 63.9, t: 3.3, kat: "Przyprawy",
    m: { łyżeczka: 3, szczypta: 0.2 }, a: ["pieprz", "pieprzu", "pieprz czarny", "pieprz mielony"] },
  { x: "błonnik", n: "Papryka słodka mielona", k: 282, b: 14.1, w: 54.0, t: 12.9, kat: "Przyprawy",
    m: { łyżeczka: 3, łyżka: 7 }, a: ["papryka słodka", "papryka mielona", "słodka papryka"] },
  { x: "błonnik", n: "Majeranek", k: 271, b: 12.7, w: 60.6, t: 7.0, kat: "Przyprawy",
    m: { łyżeczka: 1.5 }, a: ["majeranek", "majeranku"] },
  { n: "Bazylia", k: 233, b: 14.4, w: 47.8, t: 4.0, kat: "Przyprawy",
    m: { łyżeczka: 1, pęczek: 20, garść: 15 }, a: ["bazylia", "bazylii", "listki bazylii"] },
  { x: "błonnik", n: "Oregano", k: 265, b: 9.0, w: 68.9, t: 4.3, kat: "Przyprawy",
    m: { łyżeczka: 1.5 }, a: ["oregano", "zioła prowansalskie", "tymianek", "rozmaryn",
        "zioła włoskie", "ziół włoskich", "przyprawa do pizzy", "melisa", "liść melisy"] },
  { n: "Kminek", k: 375, b: 17.8, w: 44.2, t: 22.3, kat: "Przyprawy",
    m: { łyżeczka: 2 }, a: ["kminek", "kmin rzymski", "kumin"] },
  { x: "błonnik", n: "Cynamon", k: 247, b: 4.0, w: 80.6, t: 1.2, kat: "Przyprawy",
    m: { łyżeczka: 2.5 }, a: ["cynamon", "cynamonu"] },
  { x: "błonnik", n: "Liść laurowy", k: 313, b: 7.6, w: 75.0, t: 8.4, kat: "Przyprawy",
    m: { listek: 0.2, sztuka: 0.2 }, a: ["liść laurowy", "liście laurowe", "listek laurowy"] },
  { x: "błonnik", n: "Ziele angielskie", k: 263, b: 6.1, w: 72.1, t: 8.7, kat: "Przyprawy",
    m: { sztuka: 0.1, łyżeczka: 2 }, a: ["ziele angielskie", "ziela angielskiego"] },
  { n: "Curry", k: 325, b: 12.7, w: 55.8, t: 13.8, kat: "Przyprawy",
    m: { łyżeczka: 2 }, a: ["curry", "kurkuma", "imbir mielony", "garam masala"] },
  { n: "Gałka muszkatołowa", k: 525, b: 5.8, w: 49.3, t: 36.3, kat: "Przyprawy",
    m: { łyżeczka: 2, szczypta: 0.2 }, a: ["gałka muszkatołowa", "gałka"] },
  { n: "Ocet", k: 18, b: 0, w: 0.4, t: 0, kat: "Dodatki",
    m: { łyżka: 15 }, a: ["ocet", "ocet winny", "ocet balsamiczny", "octu"] },
  { n: "Musztarda", k: 66, b: 4.4, w: 5.8, t: 3.4, kat: "Dodatki",
    m: { łyżka: 16, łyżeczka: 5 }, a: ["musztarda", "musztardy"] },
  { n: "Majonez", k: 680, b: 1.1, w: 2.4, t: 74.0, kat: "Dodatki",
    m: { łyżka: 15 }, a: ["majonez", "majonezu"] },
  { n: "Ketchup", k: 102, b: 1.7, w: 24.0, t: 0.1, kat: "Dodatki",
    m: { łyżka: 17 }, a: ["ketchup", "keczup"] },
  { n: "Sos sojowy", k: 53, b: 8.1, w: 4.9, t: 0.6, kat: "Dodatki",
    m: { łyżka: 16 }, a: ["sos sojowy", "sosu sojowego"] },
  { n: "Bulion warzywny", k: 4, b: 0.2, w: 0.6, t: 0.1, kat: "Dodatki",
    m: { szklanka: 250, kostka: 10 },
    a: ["bulion", "bulionu", "rosół", "wywar", "bulion warzywny", "bulion drobiowy",
        "kostka rosołowa", "kostka bulionowa"] },
  { n: "Woda", k: 0, b: 0, w: 0, t: 0, kat: "Dodatki",
    m: { szklanka: 250, łyżka: 15 }, a: ["woda", "wody", "wrzątek", "zimna woda", "ciepła woda"] },
  { n: "Mleko kokosowe", k: 197, b: 2.0, w: 2.8, t: 21.3, kat: "Dodatki",
    m: { puszka: 400, szklanka: 240 }, a: ["mleko kokosowe"] },
  { n: "Sok jabłkowy", k: 46, b: 0.1, w: 11.3, t: 0.1, kat: "Napoje",
    m: { szklanka: 250 }, a: ["sok", "sok owocowy", "sok jabłkowy"] },

  // --- Domknięcie słownictwa: to, czego zabrakło przy pierwszym imporcie ---
  { n: "Włoszczyzna", k: 45, b: 1.3, w: 9.8, t: 0.3, kat: "Warzywa",
    m: { pęczek: 400, opakowanie: 400 }, a: ["włoszczyzna", "włoszczyzny"] },
  { n: "Sok z cytryny", k: 22, b: 0.4, w: 6.9, t: 0.2, kat: "Napoje",
    m: { łyżka: 15, sztuka: 40 }, a: ["sok z cytryny", "sok cytrynowy", "sok z limonki", "sok z połowy cytryny"] },
  { n: "Soda oczyszczona", k: 0, b: 0, w: 0, t: 0, kat: "Przyprawy",
    m: { łyżeczka: 5 }, a: ["soda oczyszczona", "sody oczyszczonej", "soda"] },
  { x: "błonnik", n: "Goździki", k: 274, b: 6.0, w: 65.5, t: 13.0, kat: "Przyprawy",
    m: { sztuka: 0.1, łyżeczka: 2 }, a: ["goździki", "goździków"] },
  { x: "błonnik", n: "Gorczyca", k: 508, b: 26.1, w: 28.1, t: 36.2, kat: "Przyprawy",
    m: { łyżka: 10, łyżeczka: 3 }, a: ["gorczyca", "gorczycy", "ziarna gorczycy"] },
  { n: "Imbir świeży", k: 80, b: 1.8, w: 17.8, t: 0.8, kat: "Przyprawy",
    m: { kawałek: 15, łyżeczka: 5 }, a: ["imbir", "imbiru", "imbir świeży", "świeży imbir"] },
  { x: "alkohol", n: "Ekstrakt waniliowy", k: 288, b: 0.1, w: 12.7, t: 0.1, kat: "Przyprawy",
    m: { łyżka: 13, łyżeczka: 4 }, a: ["ekstrakt waniliowy", "ekstrakt z wanilii", "wanilia",
        "laska wanilii"] },
  { n: "Syrop klonowy", k: 260, b: 0, w: 67.0, t: 0.1, kat: "Słodkie",
    m: { łyżka: 20 }, a: ["syrop klonowy", "syrop", "syropu"] },
  { n: "Słonina", k: 812, b: 2.9, w: 0, t: 88.7, kat: "Tłuszcze",
    a: ["słonina", "słoniny", "łój", "łoju", "łój wołowy"] },
  { n: "Jarmuż", k: 49, b: 4.3, w: 8.8, t: 0.9, kat: "Warzywa",
    m: { garść: 25 }, a: ["jarmuż", "jarmużu"] },
  { n: "Kalarepa", k: 27, b: 1.7, w: 6.2, t: 0.1, kat: "Warzywa", s: 200,
    a: ["kalarepa", "kalarepy", "kalarepka"] },
  { n: "Kiwi", k: 61, b: 1.1, w: 14.7, t: 0.5, kat: "Owoce", s: 75,
    a: ["kiwi", "owoce kiwi"] },
  { x: "alkohol", n: "Wino białe wytrawne", k: 82, b: 0.1, w: 2.6, t: 0, kat: "Dodatki",
    m: { szklanka: 240, kieliszek: 100 }, a: ["wino białe", "białe wino", "wino wytrawne", "białego wina", "wina",
        "wino czerwone", "czerwone wino", "białego wytrawnego wina"] },
  { n: "Przyprawa do zup", k: 150, b: 10.0, w: 20.0, t: 3.0, kat: "Przyprawy",
    m: { kostka: 10, łyżeczka: 4 }, a: ["przyprawa do zup", "przyprawy do zup", "maggi",
        "vegeta", "warzywko"] },
  { n: "Jarzyny mrożone", k: 45, b: 2.5, w: 8.0, t: 0.3, kat: "Warzywa",
    m: { opakowanie: 450 }, a: ["mrożone warzywa", "warzywa mrożone", "mieszanka warzywna",
        "jarzyny"] },

  { n: "Dymka", k: 32, b: 1.8, w: 7.3, t: 0.2, kat: "Warzywa",
    m: { pęczek: 100 }, a: ["dymka", "dymki", "cebula dymka", "szczypior"] },
  { n: "Rzeżucha", k: 32, b: 2.6, w: 5.5, t: 0.7, kat: "Warzywa",
    m: { łyżka: 3, opakowanie: 30 }, a: ["rzeżucha", "rzeżuchy"] },
  { n: "Sardele", k: 210, b: 20.4, w: 0, t: 14.0, kat: "Ryby",
    m: { sztuka: 8, puszka: 50 }, a: ["sardele", "sardeli", "anchois"] },
  { n: "Szałwia", k: 315, b: 10.6, w: 60.7, t: 12.8, kat: "Przyprawy",
    m: { gałązka: 2, listek: 0.5 }, a: ["szałwia", "szałwii"] },
  { n: "Sos beszamelowy", k: 120, b: 3.4, w: 8.0, t: 8.0, kat: "Dodatki",
    m: { szklanka: 250, łyżka: 20 }, a: ["sos beszamel", "beszamel", "sosu beszamel",
        "sos beszamelowy"] },
  { x: "alkohol", n: "Piwo jasne", k: 43, b: 0.5, w: 3.6, t: 0, kat: "Napoje",
    m: { szklanka: 250, kieliszek: 100 }, a: ["piwo", "piwa", "jasne piwo", "jasnego piwa"] },
  { n: "Krem karmelowy", k: 450, b: 3.0, w: 60.0, t: 22.0, kat: "Słodkie",
    m: { łyżka: 20, słoik: 400 }, a: ["krem karmelowy", "kremu karmelowego", "masa karmelowa",
        "krem karmelowy korzenny"] },

  { n: "Sos tabasco", k: 21, b: 1.3, w: 1.8, t: 0.8, kat: "Dodatki",
    m: { łyżeczka: 5, kropla: 0.05 }, a: ["tabasco", "sos tabasco", "sos chili"] },
];
