-- ============================================================
-- Grind — Migracja 0004: kuratorowany katalog ćwiczeń (PL)
-- Ćwiczenia globalne: user_id IS NULL, is_public = true, source = 'curated'
-- Import z wger (kilkaset dodatkowych pozycji + zdjęcia) robi osobny skrypt:
--   npm run import:wger
-- ============================================================

insert into public.exercise_catalog
  (user_id, is_public, source, slug, name, name_en, description, cues, mistakes,
   category, muscle_group, muscles, muscles_secondary, equipment, metric)
values

-- ---------- KLATKA / BARKI / TRICEPS ----------
(null, true, 'curated', 'wyciskanie-sztangi-lawka-plaska',
 'Wyciskanie sztangi na ławce płaskiej', 'Barbell Bench Press',
 'Połóż się na ławce tak, aby oczy były pod gryfem. Ściągnij łopatki i dociśnij je do ławki, stopy mocno na podłodze. Chwyt nieco szerszy niż barki. Opuszczaj sztangę kontrolowanie do dolnej części klatki, dotknij i wypchnij po lekkim łuku w stronę oczu.',
 array['Łopatki ściągnięte i schowane w dół przez cały ruch', 'Łokcie pod kątem ok. 45-75° do tułowia, nie na boki', 'Nadgarstek prosty, gryf nad przedramieniem'],
 array['Odbijanie sztangi od klatki', 'Odrywanie pośladków od ławki'],
 'Klatka piersiowa', 'Klatka piersiowa',
 array['klatka piersiowa'], array['triceps','przód barków'], array['sztanga','ławka'], 'weight_reps'),

(null, true, 'curated', 'wyciskanie-hantli-nad-glowa',
 'Wyciskanie hantli nad głową', 'Dumbbell Overhead Press',
 'Siedząc lub stojąc, hantle na wysokości barków, dłonie skierowane do przodu. Napnij brzuch i pośladki, żeby nie wyginać lędźwi. Wypchnij hantle w górę aż do wyprostu łokci, ramiona kończą przy uszach. Opuszczaj wolniej niż wypychasz.',
 array['Żebra ściągnięte w dół — brzuch napięty', 'Nie blokuj gwałtownie łokci', 'Hantle nad barkami, nie przed nimi'],
 array['Przeprost w odcinku lędźwiowym', 'Wypychanie tułowiem (to już push press)'],
 'Barki', 'Barki',
 array['barki'], array['triceps','góra klatki'], array['hantle'], 'weight_reps'),

(null, true, 'curated', 'wyciskanie-hantli-lawka-skosna',
 'Wyciskanie hantlami na ławce skośnej', 'Incline Dumbbell Press',
 'Ławka pod kątem 30-45°. Hantle na wysokości górnej części klatki, łopatki ściągnięte. Wypychaj hantle w górę i lekko do środka, nie stukając nimi o siebie. Opuszczaj do momentu, w którym czujesz rozciąganie w klatce, bez bólu w barku.',
 array['Kąt ławki max 45° — wyżej to już ćwiczenie na barki', 'Kontroluj fazę opuszczania 2-3 sekundy'],
 array['Zbyt duży kąt ławki i przeciążenie barków', 'Zbyt głębokie opuszczanie przy sztywnych barkach'],
 'Klatka piersiowa', 'Klatka piersiowa',
 array['górna część klatki'], array['przód barków','triceps'], array['hantle','ławka skośna'], 'weight_reps'),

(null, true, 'curated', 'prostowanie-ramion-wyciag',
 'Prostowanie ramion na wyciągu', 'Cable Triceps Pushdown',
 'Stań przed wyciągiem górnym, chwyć drążek lub linkę. Łokcie przyklejone do tułowia i nieruchome. Prostuj ramiona w dół do pełnego wyprostu, zatrzymaj na moment, wracaj kontrolowanie.',
 array['Łokcie nie wędrują do przodu ani na boki', 'Lekki skłon tułowia, ale bez bujania'],
 array['Pomaganie sobie całym ciałem', 'Zbyt duży ciężar i skrócony zakres ruchu'],
 'Ramiona', 'Triceps',
 array['triceps'], array[]::text[], array['wyciąg'], 'weight_reps'),

-- ---------- PLECY / BICEPS ----------
(null, true, 'curated', 'podciaganie-sciaganie-drazka',
 'Podciąganie / ściąganie drążka wyciągu górnego', 'Pull-up / Lat Pulldown',
 'Chwyt nachwytem, nieco szerszy niż barki. Zacznij ruch od ściągnięcia łopatek w dół, dopiero potem zginaj ramiona. Ciągnij drążek do góry klatki, klatka wypchnięta do przodu. Jeśli nie robisz jeszcze podciągnięć — ta sama technika na wyciągu górnym.',
 array['Ruch zaczyna łopatka, nie biceps', 'Klatka do drążka, lekkie odchylenie tułowia', 'Pełny zwis / pełny wyprost na górze'],
 array['Bujanie ciałem i zarzucanie', 'Ciągnięcie drążka za kark'],
 'Plecy', 'Plecy',
 array['najszerszy grzbietu'], array['biceps','tylne barki'], array['drążek','wyciąg'], 'weight_reps'),

(null, true, 'curated', 'wioslowanie-sztanga-w-opadzie',
 'Wiosłowanie sztangą w opadzie', 'Barbell Bent-over Row',
 'Sztanga przed sobą, chwyt nachwytem na szerokość barków. Zegnij biodra do ok. 45°, plecy proste, kolana lekko ugięte. Przyciągnij sztangę do dolnych żeber/pępka, łokcie blisko tułowia, ściśnij łopatki. Opuszczaj kontrolowanie.',
 array['Kręgosłup neutralny — klatka wypchnięta, wzrok w podłogę przed sobą', 'Napięty brzuch stabilizuje odcinek lędźwiowy'],
 array['Zaokrąglone plecy', 'Prostowanie się w trakcie ciągnięcia'],
 'Plecy', 'Plecy',
 array['plecy środkowe','czworoboczny'], array['biceps','tylne barki'], array['sztanga'], 'weight_reps'),

(null, true, 'curated', 'wioslowanie-hantla-jednoracz',
 'Wiosłowanie hantlą jednorącz', 'One-arm Dumbbell Row',
 'Kolano i dłoń jednej strony oprzyj na ławce, druga noga na podłodze. Plecy równolegle do podłogi, kręgosłup neutralny. Ciągnij hantel wzdłuż tułowia do biodra, łokieć blisko żeber. Na górze ściśnij łopatkę, na dole pozwól łopatce się wysunąć.',
 array['Nie rotuj tułowia, żeby dociągnąć ciężar', 'Pełny zakres: rozciągnięcie na dole, ściśnięcie na górze'],
 array['Skręcanie tułowia i praca ramieniem zamiast plecami'],
 'Plecy', 'Plecy',
 array['najszerszy grzbietu','plecy środkowe'], array['biceps'], array['hantle','ławka'], 'weight_reps'),

(null, true, 'curated', 'uginanie-ramion-sztanga',
 'Uginanie ramion ze sztangą', 'Barbell Biceps Curl',
 'Stój prosto, sztanga podchwytem na szerokość barków, łokcie przy tułowiu. Uginaj ramiona bez bujania tułowiem, na górze krótkie napięcie. Opuszczaj wolno do prawie pełnego wyprostu.',
 array['Łokcie w jednym miejscu przez cały ruch', 'Nadgarstki proste'],
 array['Odchylanie tułowia do tyłu', 'Zarzucanie ciężaru biodrami'],
 'Ramiona', 'Biceps',
 array['biceps'], array['przedramiona'], array['sztanga'], 'weight_reps'),

(null, true, 'curated', 'face-pull',
 'Face pull', 'Face Pull',
 'Linka wyciągu ustawiona na wysokości twarzy. Chwyć linkę oburącz, cofnij się do napięcia. Ciągnij do twarzy, rozwierając ręce na boki i rotując barki na zewnątrz — na końcu ruchu dłonie po bokach głowy, łokcie wysoko.',
 array['Rotacja zewnętrzna barków to sedno ćwiczenia', 'Lekki ciężar, wysokie powtórzenia, czysta technika'],
 array['Ciągnięcie samymi ramionami bez rotacji', 'Za duży ciężar i pomaganie tułowiem'],
 'Barki', 'Barki',
 array['tylne barki'], array['czworoboczny','rotatory'], array['wyciąg'], 'weight_reps'),

-- ---------- NOGI / POŚLADKI ----------
(null, true, 'curated', 'martwy-ciag-rumunski-hantle',
 'Martwy ciąg rumuński z hantlami', 'Romanian Deadlift (Dumbbell)',
 'Stań w lekkim rozkroku, hantle przed udami. Kolana lekko ugięte i nieruchome. Odsuwaj biodra do tyłu, prowadząc hantle blisko nóg, aż poczujesz mocne rozciąganie dwugłowych. Wróć wypychając biodra do przodu i ściskając pośladki.',
 array['Ruch z biodra, nie z kolana — to nie przysiad', 'Hantle jadą po nogach jak po szynach', 'Zakres do granicy prostych pleców, nie niżej'],
 array['Zaokrąglanie dolnego odcinka pleców', 'Zginanie kolan i zamiana ćwiczenia w przysiad'],
 'Nogi', 'Dwugłowy uda',
 array['dwugłowy uda','pośladki'], array['prostowniki grzbietu'], array['hantle'], 'weight_reps'),

(null, true, 'curated', 'prostownik-nog',
 'Prostownik nóg (maszyna)', 'Leg Extension',
 'Usiądź w maszynie, wałek tuż nad kostkami, plecy oparte. Prostuj nogi kontrolowanie do pełnego wyprostu, przytrzymaj chwilę napięcie, wracaj wolno. Ćwiczenie izolowane na czworogłowy — przy rehabilitacji kolana zwracaj uwagę na zakres, który nie prowokuje bólu.',
 array['REHAB: zacznij od zakresu bezbolesnego, np. tylko ostatnie 30° wyprostu', 'Tempo powolne, bez szarpania', 'Oś obrotu maszyny na wysokości kolana'],
 array['Zbyt duży ciężar i szarpanie w dolnej fazie', 'Ignorowanie bólu rzepkowo-udowego'],
 'Nogi', 'Czworogłowy',
 array['czworogłowy uda'], array[]::text[], array['maszyna'], 'weight_reps'),

(null, true, 'curated', 'odwodziciele-przywodziciele-bioder',
 'Odwodziciele / przywodziciele bioder (maszyna)', 'Hip Abduction / Adduction',
 'Usiądź w maszynie, plecy oparte, wałki po zewnętrznej (odwodzenie) lub wewnętrznej (przywodzenie) stronie ud. Rozsuwaj lub zsuwaj kolana kontrolowanie, bez bujania tułowiem. Krótka pauza w końcowym zakresie.',
 array['Lekki skłon tułowia do przodu mocniej angażuje pośladek średni', 'Tempo równe w obie strony'],
 array['Odbijanie ciężaru i praca rozpędem'],
 'Nogi', 'Pośladki',
 array['pośladek średni'], array['przywodziciele'], array['maszyna'], 'weight_reps'),

(null, true, 'curated', 'hip-thrust',
 'Wyprosty bioder na wyciągu / hip thrust', 'Hip Thrust',
 'Oprzyj górę pleców o ławkę, sztanga (z podkładką) na biodrach, stopy w rozkroku na szerokość bioder. Wypchnij biodra w górę, aż tułów i uda utworzą linię prostą, mocno ściskając pośladki. Broda przyklejona do klatki, żebra w dół.',
 array['Szczyt ruchu to ściśnięcie pośladków, nie przeprost lędźwi', 'Piszczel pionowo w górnej pozycji — dobierz odległość stóp'],
 array['Przeprost w lędźwiach zamiast wyprostu bioder', 'Odrywanie pięt od podłogi'],
 'Nogi', 'Pośladki',
 array['pośladki'], array['dwugłowy uda'], array['sztanga','ławka'], 'weight_reps'),

(null, true, 'curated', 'lydki-maszyna',
 'Łydki na maszynie', 'Calf Raise',
 'Śródstopie na podeście, pięty swobodnie w dole. Opuść pięty maksymalnie nisko (rozciągnięcie), potem wypchnij się na palce najwyżej jak potrafisz. Pauza na górze 1 sekunda.',
 array['Pełny zakres: głęboko w dół, wysoko w górę', 'Kolana wyprostowane (brzuchaty) lub ugięte (płaszczkowaty)'],
 array['Krótkie, sprężynujące ruchy bez rozciągnięcia'],
 'Nogi', 'Łydki',
 array['łydki'], array[]::text[], array['maszyna'], 'weight_reps'),

(null, true, 'curated', 'martwy-ciag-sztanga',
 'Martwy ciąg sztangą', 'Barbell Deadlift',
 'Sztanga nad śródstopiem, chwyt na szerokość barków. Zejdź do gryfu odsuwając biodra, klatka wypchnięta, plecy proste. Napnij ciało, jakbyś chciał odepchnąć podłogę stopami. Sztanga jedzie pionowo w górę tuż przy nogach. Blokuj biodra ściskając pośladki, bez odchylania się do tyłu.',
 array['Napięcie zanim ruszysz ciężar — wyciągnij luz z gryfu', 'Barki lekko przed gryfem w pozycji startowej', 'Kręgosłup neutralny od głowy po miednicę'],
 array['Zaokrąglone plecy', 'Podnoszenie bioder szybciej niż sztangi', 'Odchylanie tułowia w tył na zakończenie'],
 'Nogi', 'Cały łańcuch tylny',
 array['prostowniki grzbietu','pośladki','dwugłowy uda'], array['czworoboczny','przedramiona'], array['sztanga'], 'weight_reps'),

(null, true, 'curated', 'wyciskanie-nog-suwnica',
 'Wyciskanie nóg na suwnicy (leg press)', 'Leg Press',
 'Stopy na platformie na szerokość bioder, mniej więcej na jej środku. Opuszczaj platformę do momentu, w którym uda zbliżają się do klatki, ale miednica nie odrywa się od oparcia. Wypychaj piętami, nie blokując gwałtownie kolan.',
 array['REHAB: ustal zakres, w którym kolano nie boli, i trzymaj się go', 'Kolana w linii ze stopami, nie do środka', 'Dolny odcinek pleców przyklejony do oparcia'],
 array['Odrywanie miednicy od oparcia w dolnej fazie', 'Blokowanie kolan z impetem na górze'],
 'Nogi', 'Czworogłowy',
 array['czworogłowy uda','pośladki'], array['dwugłowy uda'], array['maszyna'], 'weight_reps'),

(null, true, 'curated', 'goblet-squat',
 'Przysiad z hantlą (goblet squat)', 'Goblet Squat',
 'Trzymaj hantel lub kettlebell pionowo przy klatce, łokcie skierowane w dół. Stopy na szerokość barków, palce lekko na zewnątrz. Schodź w dół prowadząc kolana na zewnątrz, tułów możliwie pionowo. Zejdź tak nisko, jak pozwala mobilność bez zaokrąglania pleców.',
 array['Ciężar przy klatce naturalnie utrzymuje pionową sylwetkę', 'Kolana podążają za palcami stóp', 'Cały czas nacisk na całą stopę'],
 array['Zapadanie kolan do środka', 'Odrywanie pięt'],
 'Nogi', 'Czworogłowy',
 array['czworogłowy uda','pośladki'], array['core'], array['hantle','kettlebell'], 'weight_reps'),

(null, true, 'curated', 'przysiad-ze-sztanga',
 'Przysiad ze sztangą (back squat)', 'Barbell Back Squat',
 'Sztanga na górnej części pleców (nie na karku), łopatki ściągnięte. Stopy na szerokość barków. Wdech, napięcie brzucha, zejście z jednoczesnym zgięciem bioder i kolan. Zejdź co najmniej do równoległości ud z podłogą, wstań wypychając podłogę stopami.',
 array['Zejście kontrolowane, wyjście dynamiczne', 'Tułów i sztanga poruszają się w pionie nad śródstopiem', 'Faza 2 planu — wprowadzaj dopiero po zgodzie fizjoterapeuty'],
 array['Zapadanie kolan do środka', 'Zaokrąglenie lędźwi w dole (butt wink) przy zbyt głębokim zejściu'],
 'Nogi', 'Czworogłowy',
 array['czworogłowy uda','pośladki'], array['prostowniki grzbietu','core'], array['sztanga','stojaki'], 'weight_reps'),

(null, true, 'curated', 'wypady',
 'Wypady', 'Lunges',
 'Zrób krok do przodu (lub w tył — łagodniejsze dla kolana), opuszczając tylne kolano w stronę podłogi. Oba kolana zginają się do ok. 90°. Przednia piszczel możliwie pionowo. Wypchnij się piętą przedniej nogi z powrotem do stania.',
 array['Wypad w tył mniej obciąża rzepkę — dobry wybór po kontuzji', 'Tułów pionowo, wzrok przed siebie', 'Kolano przedniej nogi stabilne, nie ucieka do środka'],
 array['Zbyt krótki krok i przeciążenie stawu kolanowego', 'Utrata równowagi z powodu zbyt wąskiego ustawienia stóp'],
 'Nogi', 'Czworogłowy',
 array['czworogłowy uda','pośladki'], array['dwugłowy uda','core'], array['hantle','masa ciała'], 'weight_reps'),

(null, true, 'curated', 'box-jump',
 'Wyskoki plyometryczne (box jump)', 'Box Jump',
 'Stań przed skrzynią na odległość pół kroku. Zamachnij ramionami, ugnij biodra i kolana, wyskocz miękko lądując na skrzyni na całej stopie w półprzysiadzie. Zejdź ze skrzyni krokiem, nie zeskakuj.',
 array['Miękkie lądowanie — to nie skok na wysokość, tylko trening amortyzacji', 'Zejście krokiem oszczędza kolana', 'Faza 2 — dopiero po zgodzie fizjoterapeuty'],
 array['Zeskakiwanie ze skrzyni w dół (duże obciążenie kolan)', 'Zbyt wysoka skrzynia i lądowanie w głębokim przysiadzie'],
 'Nogi', 'Moc',
 array['czworogłowy uda','pośladki','łydki'], array['core'], array['skrzynia'], 'reps'),

-- ---------- CORE ----------
(null, true, 'curated', 'plank',
 'Plank (deska)', 'Plank',
 'Podpór na przedramionach i palcach stóp. Łokcie pod barkami. Ciało tworzy prostą linię od głowy do pięt: pośladki ściśnięte, brzuch napięty, miednica podwinięta. Oddychaj spokojnie, nie wstrzymuj oddechu.',
 array['Aktywnie ściągaj żebra w dół i podwiń miednicę', 'Jakość ważniejsza niż czas — przerwij gdy biodra opadają'],
 array['Opadające biodra i przeprost w lędźwiach', 'Uniesiony wysoko tyłek'],
 'Core', 'Core',
 array['mięsień poprzeczny brzucha','proste brzucha'], array['barki','pośladki'], array['masa ciała'], 'time'),

(null, true, 'curated', 'deska-boczna',
 'Deska boczna', 'Side Plank',
 'Połóż się na boku, podpór na przedramieniu, łokieć pod barkiem. Unieś biodra tak, aby ciało tworzyło prostą linię. Górna ręka na biodrze lub w górze. Utrzymaj pozycję, nie pozwalając biodrom opaść ani obrócić się do przodu.',
 array['Biodra wysoko, klatka otwarta', 'Wersja łatwiejsza: podpór na kolanach'],
 array['Rotacja tułowia do przodu', 'Opadające biodro'],
 'Core', 'Skośne brzucha',
 array['skośne brzucha'], array['pośladek średni','barki'], array['masa ciała'], 'time'),

(null, true, 'curated', 'dead-bug',
 'Martwy robak (dead bug)', 'Dead Bug',
 'Leż na plecach, biodra i kolana zgięte pod kątem 90°, ramiona wyprostowane w górę. Dociśnij dolny odcinek pleców do podłogi. Powoli opuszczaj jednocześnie przeciwną rękę i nogę, nie tracąc kontaktu lędźwi z podłogą. Wróć i zmień stronę.',
 array['Lędźwie przyklejone do podłogi przez cały ruch — to jedyny warunek poprawności', 'Wydech przy opuszczaniu kończyn', 'Skróć zakres, jeśli plecy się odrywają'],
 array['Odrywanie lędźwi od podłogi', 'Zbyt szybkie tempo'],
 'Core', 'Core',
 array['mięsień poprzeczny brzucha'], array['stabilizacja lędźwi'], array['masa ciała'], 'reps'),

(null, true, 'curated', 'rotacje-tulowia-wyciag',
 'Rotacje tułowia na wyciągu', 'Cable Woodchop / Torso Rotation',
 'Stań bokiem do wyciągu, chwyć uchwyt oburącz z wyprostowanymi ramionami. Stopy stabilnie, biodra i tułów rotują razem. Obracaj tułów w stronę przeciwną do wyciągu, kończąc ruch z ramionami przed sobą. Wracaj kontrolowanie, nie pozwalając ciężarowi wyrwać cię z pozycji.',
 array['Rotacja z klatki piersiowej i bioder, ramiona tylko przenoszą siłę', 'Biodra mogą się obracać — nie blokuj ich na siłę'],
 array['Praca samymi rękami', 'Zbyt duży ciężar i utrata kontroli w fazie powrotu'],
 'Core', 'Skośne brzucha',
 array['skośne brzucha'], array['core','biodra'], array['wyciąg'], 'weight_reps'),

-- ---------- MMA / SIŁA FUNKCJONALNA ----------
(null, true, 'curated', 'rzuty-pilka-lekarska-rotacyjne',
 'Rotacyjne rzuty piłką lekarską', 'Medicine Ball Rotational Throw',
 'Stań bokiem do ściany w rozkroku, piłka lekarska oburącz przy biodrze dalszym od ściany. Zrotuj biodra i tułów w stronę ściany, wyrzucając piłkę z pełną mocą. Złap odbitą piłkę lub podnieś i powtórz. Ruch napędzają biodra, nie ramiona.',
 array['Maksymalna intencja — to trening mocy, nie wytrzymałości', 'Tylna pięta odrywa się i rotuje jak przy ciosie', 'Krótkie serie, pełna przerwa między nimi'],
 array['Rzucanie samymi rękami', 'Zbyt ciężka piłka i wolny ruch'],
 'MMA', 'Moc rotacyjna',
 array['skośne brzucha','biodra'], array['barki','klatka piersiowa'], array['piłka lekarska'], 'reps'),

(null, true, 'curated', 'rotacje-kettlebell',
 'Rotacje z kettlebell', 'Kettlebell Rotation (Halo / Around the World)',
 'Trzymaj kettlebell oburącz przed klatką, stopy stabilnie w rozkroku. Prowadź ciężar po łuku wokół tułowia lub rotuj tułów z ciężarem, utrzymując napięty brzuch. Kontroluj ciężar w każdym punkcie toru — celem jest odporność na skręcenie, nie prędkość.',
 array['Napięty brzuch przez cały ruch', 'Tempo kontrolowane, bez rzucania ciężarem'],
 array['Wyginanie się w lędźwiach przy przenoszeniu ciężaru za głowę'],
 'MMA', 'Core',
 array['skośne brzucha','core'], array['barki'], array['kettlebell'], 'weight_reps'),

(null, true, 'curated', 'spacer-farmera',
 'Spacer farmera (farmer''s walk)', 'Farmer''s Walk',
 'Podnieś ciężkie hantle lub kettlebelle po bokach ciała. Klatka wypchnięta, łopatki ściągnięte, brzuch napięty. Idź równym, pewnym krokiem na zadany dystans, nie pozwalając ciężarowi wyginać tułowia na boki.',
 array['Sylwetka wyprostowana — jakbyś niósł pełne wiadra wody, nie zgarbiony', 'Krótkie, kontrolowane kroki', 'Chwyt jest zwykle ogniwem limitującym — i o to chodzi'],
 array['Garbienie się pod ciężarem', 'Bujanie tułowiem na boki'],
 'MMA', 'Chwyt / core',
 array['przedramiona','czworoboczny','core'], array['pośladki','nogi'], array['hantle','kettlebell'], 'distance'),

(null, true, 'curated', 'wisy-na-drazku',
 'Wisy na drążku (dead hang)', 'Dead Hang',
 'Zwiśnij na drążku na wyprostowanych ramionach, chwyt na szerokość barków. Barki nie mogą być całkowicie bierne — lekko ściągnij łopatki, żeby nie wisieć na torebce stawowej. Oddychaj spokojnie i utrzymaj zwis.',
 array['Lekka aktywacja łopatek zamiast całkowitego rozluźnienia', 'Świetne dla chwytu i dekompresji kręgosłupa'],
 array['Całkowicie bierny zwis na luźnych barkach przy słabym obręczu barkowym'],
 'MMA', 'Chwyt',
 array['przedramiona'], array['najszerszy grzbietu','barki'], array['drążek'], 'time'),

(null, true, 'curated', 'deep-squat-hold',
 'Deep squat hold', 'Deep Squat Hold',
 'Zejdź do najgłębszego przysiadu, jaki pozwala Ci mobilność, stopy płasko na podłodze. Łokcie oprzyj o wewnętrzne strony kolan i delikatnie rozpychaj je na zewnątrz. Utrzymaj pozycję, oddychając spokojnie i z każdym wydechem schodząc odrobinę niżej.',
 array['Pięty na podłodze — jeśli się odrywają, podłóż pod nie mały klin', 'Klatka wypchnięta, plecy możliwie proste'],
 array['Zaokrąglone plecy i całkowite zapadnięcie się w pozycji'],
 'Mobilność', 'Mobilność bioder',
 array['biodra','kostki'], array['przywodziciele'], array['masa ciała'], 'time'),

(null, true, 'curated', 'rotacje-bioder-mobilnosc',
 'Rotacje bioder / mobilność w kółku', 'Hip CARs / Hip Mobility Circuit',
 'Seria kontrolowanych ruchów w pełnym zakresie stawu biodrowego: krążenia nogą w podporze klęcznym, otwieranie i zamykanie biodra, przejścia 90/90. Ruch wolny, kontrolowany, bez kompensacji tułowiem. Jedna runda to komplet ruchów na obie strony.',
 array['Wolno i kontrolowanie — szukasz zakresu, nie rozpędu', 'Tułów nieruchomy, pracuje wyłącznie biodro'],
 array['Kompensowanie ograniczonego zakresu ruchem kręgosłupa'],
 'Mobilność', 'Mobilność bioder',
 array['biodra'], array['core'], array['masa ciała'], 'rounds'),

(null, true, 'curated', 'stretch-90-90',
 '90/90 hip stretch', '90/90 Hip Stretch',
 'Usiądź na podłodze: przednia noga zgięta pod kątem 90° przed sobą, tylna noga zgięta pod 90° z boku. Plecy proste. Pochyl tułów nad przednią nogą, żeby rozciągnąć zewnętrzną część biodra. Przejdź płynnie na drugą stronę, przenosząc kolana nad podłogą.',
 array['Plecy proste — pochylenie idzie z biodra', 'Płynne przejścia między stronami to też trening mobilności'],
 array['Zaokrąglanie pleców zamiast zgięcia w biodrze'],
 'Mobilność', 'Mobilność bioder',
 array['biodra','pośladki'], array[]::text[], array['masa ciała'], 'time'),

-- ---------- KONDYCJA ----------
(null, true, 'curated', 'interwaly-rower-ergometr',
 'Rower stacjonarny / ergometr wioślarski — interwały', 'Bike / Rower Intervals',
 'Rozgrzewka 3-5 minut spokojnie. Następnie interwały, np. 30 sekund mocno / 90 sekund luźno, przez 15-20 minut łącznie. Zakończ 3 minutami spokojnego kręcenia. Rower i ergometr są bezpieczne dla kolana — brak fazy lotu i uderzeń.',
 array['REHAB: rower ma niski wpływ na staw kolanowy — pierwszy wybór na kondycję', 'Siodełko na wysokości bioder, kolano lekko ugięte w dolnym położeniu', 'Intensywność mierz oddechem: mocno = nie da się mówić zdaniami'],
 array['Zbyt niskie siodełko i przeciążenie rzepki', 'Robienie interwałów w bólu'],
 'Kondycja', 'Kondycja',
 array['nogi','układ krążenia'], array[]::text[], array['rower','ergometr'], 'time'),

-- ---------- ROZCIĄGANIE (wg zaleceń fizjo) ----------
(null, true, 'curated', 'stretch-czworoglowy-stojacy',
 'Rozciąganie czworogłowego — stojące', 'Standing Quad Stretch',
 'Stojąc, złap za kostkę i przyciągnij piętę do pośladka. Kolana trzymaj obok siebie, miednicę podwiń (ściśnij pośladek), żeby rozciągnąć również mięsień prosty uda. Przytrzymaj się czegoś dla równowagi.',
 array['Podwinięcie miednicy to klucz — bez tego rozciągasz o połowę mniej', 'Kolana razem, nie odchylaj rozciąganej nogi na bok'],
 array['Wyginanie się w lędźwiach zamiast rozciągania uda'],
 'Rozciąganie', 'Czworogłowy',
 array['czworogłowy uda'], array[]::text[], array['masa ciała'], 'time'),

(null, true, 'curated', 'stretch-czworoglowy-klek',
 'Rozciąganie czworogłowego — klęk (half-kneeling)', 'Half-kneeling Quad Stretch',
 'Przyklęknij na jednym kolanie (podłóż matę), drugą nogę ustaw z przodu pod kątem 90°. Podwiń miednicę i delikatnie przesuń biodro do przodu. Dla mocniejszego rozciągania oprzyj stopę tylnej nogi o ścianę lub złap ją ręką.',
 array['Miednica podwinięta zanim przesuniesz biodro do przodu', 'Tułów pionowo, nie wyginaj lędźwi'],
 array['Przeprost w dolnym odcinku pleców udający zakres w biodrze'],
 'Rozciąganie', 'Czworogłowy',
 array['czworogłowy uda','zginacze bioder'], array[]::text[], array['mata'], 'time'),

(null, true, 'curated', 'stretch-czworoglowy-lezacy',
 'Rozciąganie czworogłowego — leżące', 'Lying Quad Stretch',
 'Połóż się na boku lub na brzuchu. Złap kostkę nogi górnej i przyciągnij piętę do pośladka, utrzymując kolana blisko siebie i podwiniętą miednicę. Najłagodniejsza wersja — dobra gdy równowaga w staniu przeszkadza.',
 array['Brzuch napięty, żeby nie wyginać lędźwi', 'Oddychaj spokojnie, nie sprężynuj'],
 array['Odchylanie kolana na bok'],
 'Rozciąganie', 'Czworogłowy',
 array['czworogłowy uda'], array[]::text[], array['mata'], 'time'),

(null, true, 'curated', 'stretch-dwuglowy-siad-prosty',
 'Rozciąganie dwugłowego — siad prosty', 'Seated Hamstring Stretch',
 'Usiądź z wyprostowanymi nogami (lub jedną wyprostowaną, drugą zgiętą). Plecy proste, klatka wypchnięta. Pochylaj tułów z biodra w stronę stóp, aż poczujesz rozciąganie z tyłu uda. Nie zaokrąglaj pleców, żeby sięgnąć dalej.',
 array['Zgięcie z biodra, nie z kręgosłupa — mniejszy zakres, większy efekt', 'Palce stopy przyciągnięte do siebie zwiększa rozciąganie'],
 array['Zaokrąglanie pleców i "sięganie do palców" za wszelką cenę'],
 'Rozciąganie', 'Dwugłowy uda',
 array['dwugłowy uda'], array['łydki'], array['mata'], 'time'),

(null, true, 'curated', 'stretch-dwuglowy-pasek',
 'Rozciąganie dwugłowego z paskiem (leżąc)', 'Supine Hamstring Stretch with Strap',
 'Połóż się na plecach, zarzuć pasek lub ręcznik na śródstopie jednej nogi. Wyprostuj tę nogę i przyciągaj ją paskiem w swoją stronę, druga noga zgięta lub wyprostowana na podłodze. Lędźwie przyklejone do podłogi.',
 array['Najbezpieczniejsza wersja dla kręgosłupa — kontrolujesz zakres paskiem', 'Kolano rozciąganej nogi wyprostowane'],
 array['Odrywanie miednicy od podłogi', 'Zginanie kolana, żeby "wyciągnąć" większy zakres'],
 'Rozciąganie', 'Dwugłowy uda',
 array['dwugłowy uda'], array[]::text[], array['pasek','mata'], 'time'),

(null, true, 'curated', 'stretch-standing-forward-fold',
 'Skłon w przód w staniu (standing forward fold)', 'Standing Forward Fold',
 'Stań w lekkim rozkroku, kolana leciutko ugięte. Zginaj się z biodra, pozwalając tułowiu i głowie zwisnąć swobodnie. Rozluźnij kark. Aby zwiększyć rozciąganie, powoli prostuj kolana, ale nigdy nie blokuj ich na siłę.',
 array['Rozluźniona góra ciała, ciężar tułowia robi robotę', 'Wychodź z pozycji rolując kręgosłup powoli'],
 array['Blokowanie kolan i wymuszanie zakresu', 'Gwałtowne wyprostowanie się do stania'],
 'Rozciąganie', 'Dwugłowy uda',
 array['dwugłowy uda','prostowniki grzbietu'], array['łydki'], array['masa ciała'], 'time'),

(null, true, 'curated', 'stretch-figure-four',
 'Figure-four (leżąc)', 'Supine Figure-Four Stretch',
 'Leżąc na plecach, załóż kostkę jednej nogi na udo drugiej tuż nad kolanem, tworząc "czwórkę". Chwyć za udo nogi podpierającej i przyciągnij ją do klatki. Rozciąganie poczujesz w pośladku nogi założonej.',
 array['Głowa i barki na podłodze, nie unoś się do nóg', 'Delikatnie odpychaj założone kolano na zewnątrz'],
 array['Napinanie karku przy przyciąganiu nogi'],
 'Rozciąganie', 'Pośladki',
 array['pośladki','gruszkowaty'], array[]::text[], array['mata'], 'time'),

(null, true, 'curated', 'stretch-pigeon',
 'Pigeon (siedząc)', 'Pigeon Pose',
 'Z pozycji podporu przenieś jedno kolano do przodu, kładąc piszczel skośnie pod tułowiem, druga noga wyprostowana z tyłu. Biodra ustawione równo. Opuszczaj tułów nad przednią nogą tak głęboko, jak pozwala biodro.',
 array['Biodra równolegle — nie zwalaj ciężaru na jeden pośladek', 'Wersja łatwiejsza: figure-four leżąc'],
 array['Skręcanie miednicy', 'Ból po wewnętrznej stronie kolana przedniej nogi — natychmiast zmniejsz zakres'],
 'Rozciąganie', 'Pośladki',
 array['pośladki','gruszkowaty'], array['zginacze bioder'], array['mata'], 'time'),

(null, true, 'curated', 'stretch-knee-to-chest',
 'Kolano do klatki (knee-to-chest)', 'Knee-to-Chest Stretch',
 'Leżąc na plecach, przyciągnij jedno kolano do klatki, obejmując je rękami. Druga noga wyprostowana na podłodze lub zgięta ze stopą na podłodze. Lędźwie dociśnięte do podłoża. Delikatne rozciąganie pośladka i dolnego odcinka pleców.',
 array['Ruch łagodny, dobry na rozgrzewkę i schłodzenie', 'Wersja z obiema nogami rozluźnia lędźwie'],
 array['Szarpanie kolana do klatki'],
 'Rozciąganie', 'Pośladki',
 array['pośladki','dolny odcinek pleców'], array[]::text[], array['mata'], 'time')

on conflict (slug) where user_id is null do nothing;
